# Generated by Django 3.1.4 on 2021-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Civil', '0008_auto_20210621_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideforphd',
            name='phd_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phd',
            name='phd_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventconductedorattended',
            name='event_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='eventconductedorattended',
            name='nameof_event',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='guestlecorganizedordelivered',
            name='subject',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
