# Generated by Django 3.1.4 on 2021-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0019_phd_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideforphd',
            name='academic_year',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
