# Generated by Django 3.1.4 on 2021-06-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0021_auto_20210626_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideforphd',
            name='phd_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
